// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/social-kpis.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [
      { type: "text", text: "N\xE3o autenticado. Conecte-se com uma conta aprovada do Hopi Hari Insights." }
    ],
    isError: true
  };
}
function toolError(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function windowDates(days) {
  const end = /* @__PURE__ */ new Date();
  const start = new Date(end.getTime() - days * 24 * 3600 * 1e3);
  return { start: start.toISOString().slice(0, 10), end: end.toISOString().slice(0, 10) };
}

// src/lib/mcp/tools/social-kpis.ts
var social_kpis_default = defineTool({
  name: "get_social_kpis",
  title: "KPIs das redes sociais",
  description: "Retorna KPIs por rede social (posts, curtidas, coment\xE1rios, compartilhamentos, views, seguidores e taxa de engajamento) em uma janela de dias.",
  inputSchema: {
    days: z.number().int().min(1).max(365).default(30).describe("Tamanho da janela em dias (padr\xE3o 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { start, end } = windowDates(days ?? 30);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_platform_kpis", { _start: start, _end: end });
    if (error) return toolError(error.message);
    return jsonResult({ period: { start, end }, platforms: data ?? [] });
  }
});

// src/lib/mcp/tools/top-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var top_posts_default = defineTool2({
  name: "list_top_posts",
  title: "Melhores posts",
  description: "Lista os posts com melhor desempenho em uma rede social (ou em todas) dentro de uma janela de dias, com m\xE9tricas e link.",
  inputSchema: {
    platform: z2.enum(["all", "instagram", "tiktok", "facebook", "youtube", "linkedin"]).default("all").describe("Rede social a consultar."),
    days: z2.number().int().min(1).max(365).default(30).describe("Janela em dias (padr\xE3o 30)."),
    limit: z2.number().int().min(1).max(25).default(5).describe("Quantidade de posts (padr\xE3o 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ platform, days, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { start, end } = windowDates(days ?? 30);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_top_posts", {
      _platform: platform === "all" ? null : platform,
      _start: start,
      _end: end,
      _limit: limit ?? 5
    });
    if (error) return toolError(error.message);
    return jsonResult({ period: { start, end }, platform: platform ?? "all", posts: data ?? [] });
  }
});

// src/lib/mcp/tools/follower-growth.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var NETS = ["instagram", "tiktok", "facebook", "youtube", "linkedin"];
var follower_growth_default = defineTool3({
  name: "get_follower_growth",
  title: "Crescimento de seguidores",
  description: "Retorna o n\xFAmero atual de seguidores por rede, o total agregado e o crescimento no per\xEDodo pedido, usando o log di\xE1rio oficial.",
  inputSchema: {
    days: z3.number().int().min(1).max(365).default(30).describe("Janela de compara\xE7\xE3o em dias (padr\xE3o 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("follower_daily").select("reading_date,instagram,tiktok,facebook,youtube,linkedin,total").order("reading_date", { ascending: false }).limit(400);
    if (error) return toolError(error.message);
    const rows = data ?? [];
    if (rows.length === 0) return toolError("Nenhuma leitura de seguidores registrada.");
    const latest = rows[0];
    const cutoff = new Date(Date.now() - (days ?? 30) * 24 * 3600 * 1e3).toISOString().slice(0, 10);
    const baseline = rows.find((r) => r.reading_date <= cutoff) ?? rows[rows.length - 1];
    const sum = (r) => NETS.reduce((s, n) => s + (Number(r[n]) || 0), 0);
    const byNetwork = NETS.map((n) => {
      const current = Number(latest[n]) || 0;
      const before = Number(baseline[n]) || 0;
      return {
        network: n,
        followers: current,
        gained: current - before,
        growth_pct: before ? Number(((current - before) / before * 100).toFixed(2)) : null
      };
    });
    return jsonResult({
      latest_reading: latest.reading_date,
      baseline_reading: baseline.reading_date,
      total_followers: sum(latest),
      total_gained: sum(latest) - sum(baseline),
      by_network: byNetwork
    });
  }
});

// src/lib/mcp/tools/reputation.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.25.76";
var reputation_default = defineTool4({
  name: "get_reputation_overview",
  title: "Reputa\xE7\xE3o (ReclameAqui / TripAdvisor)",
  description: "Resumo das avalia\xE7\xF5es coletadas: volume, sentimento, nota m\xE9dia e principais reclama\xE7\xF5es por fonte em uma janela de dias.",
  inputSchema: {
    days: z4.number().int().min(1).max(730).default(90).describe("Janela em dias (padr\xE3o 90)."),
    source: z4.enum(["all", "reclameaqui", "tripadvisor"]).default("all").describe("Fonte das avalia\xE7\xF5es.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, source }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const since = new Date(Date.now() - (days ?? 90) * 24 * 3600 * 1e3).toISOString();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("reputation_reviews").select("source,rating,sentiment,category,title,ai_summary,published_at,responded_at,resolved").gte("published_at", since).order("published_at", { ascending: false }).limit(500);
    if (source && source !== "all") query = query.eq("source", source);
    const { data, error } = await query;
    if (error) return toolError(error.message);
    const rows = data ?? [];
    if (rows.length === 0) return jsonResult({ since, reviews: 0, note: "Nenhuma avalia\xE7\xE3o no per\xEDodo." });
    const ratings = rows.map((r) => Number(r.rating)).filter((n) => Number.isFinite(n));
    const byCategory = /* @__PURE__ */ new Map();
    for (const r of rows) {
      const key = r.category ?? "sem categoria";
      byCategory.set(key, (byCategory.get(key) ?? 0) + 1);
    }
    return jsonResult({
      since,
      reviews: rows.length,
      avg_rating: ratings.length ? Number((ratings.reduce((s, n) => s + n, 0) / ratings.length).toFixed(2)) : null,
      negative: rows.filter((r) => r.sentiment === "negative").length,
      neutral: rows.filter((r) => r.sentiment === "neutral").length,
      positive: rows.filter((r) => r.sentiment === "positive").length,
      answered: rows.filter((r) => r.responded_at != null).length,
      resolved: rows.filter((r) => r.resolved).length,
      top_categories: [...byCategory].sort((a, b) => b[1] - a[1]).slice(0, 8).map(([category, reviews]) => ({ category, reviews })),
      recent: rows.slice(0, 5).map((r) => ({
        source: r.source,
        published_at: r.published_at,
        rating: r.rating,
        sentiment: r.sentiment,
        title: r.title,
        summary: r.ai_summary
      }))
    });
  }
});

// src/lib/mcp/tools/park-performance.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z5 } from "npm:zod@^3.25.76";
var park_performance_default = defineTool5({
  name: "get_park_performance",
  title: "P\xFAblico e consumo no parque",
  description: "P\xFAblico mensal do parque e receita per capita por categoria (A&B, Mercadorias, Jogos) para um ano, com dias de opera\xE7\xE3o.",
  inputSchema: {
    year: z5.number().int().min(1999).max(2100).describe("Ano a consultar, ex.: 2026.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const [publicRes, perCapitaRes] = await Promise.all([
      supabase.from("park_public_monthly").select("year,month,visitors,open_days").eq("year", year).order("month"),
      supabase.from("park_percapita_daily").select("date,category,public,revenue,penetration_pct").gte("date", `${year}-01-01`).lte("date", `${year}-12-31`).limit(5e3)
    ]);
    if (publicRes.error) return toolError(publicRes.error.message);
    if (perCapitaRes.error) return toolError(perCapitaRes.error.message);
    const agg = /* @__PURE__ */ new Map();
    for (const r of perCapitaRes.data ?? []) {
      const e = agg.get(r.category) ?? { revenue: 0, publicSum: 0, days: 0 };
      e.revenue += Number(r.revenue) || 0;
      e.publicSum += Number(r.public) || 0;
      e.days += 1;
      agg.set(r.category, e);
    }
    const months = publicRes.data ?? [];
    return jsonResult({
      year,
      total_visitors: months.reduce((s, m) => s + (Number(m.visitors) || 0), 0),
      monthly_visitors: months,
      per_capita_by_category: [...agg].map(([category, e]) => ({
        category,
        revenue: Number(e.revenue.toFixed(2)),
        days_with_data: e.days,
        per_capita: e.publicSum ? Number((e.revenue / e.publicSum).toFixed(2)) : null
      }))
    });
  }
});

// src/lib/mcp/tools/sales-overview.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z6 } from "npm:zod@^3.25.76";
var sales_overview_default = defineTool6({
  name: "get_sales_overview",
  title: "Vendas por canal",
  description: "Receita e quantidade vendida por canal em um ano, com evolu\xE7\xE3o mensal e compara\xE7\xE3o com o ano anterior.",
  inputSchema: {
    year: z6.number().int().min(2015).max(2100).describe("Ano a consultar, ex.: 2026.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sales_revenue_monthly").select("channel,year,month,quantity,revenue").in("year", [year, year - 1]).limit(5e3);
    if (error) return toolError(error.message);
    const rows = data ?? [];
    const summarize = (y) => {
      const subset = rows.filter((r) => r.year === y);
      const byChannel = /* @__PURE__ */ new Map();
      for (const r of subset) {
        const e = byChannel.get(r.channel) ?? { revenue: 0, quantity: 0 };
        e.revenue += Number(r.revenue) || 0;
        e.quantity += Number(r.quantity) || 0;
        byChannel.set(r.channel, e);
      }
      return {
        year: y,
        revenue: Number(subset.reduce((s, r) => s + (Number(r.revenue) || 0), 0).toFixed(2)),
        quantity: subset.reduce((s, r) => s + (Number(r.quantity) || 0), 0),
        by_channel: [...byChannel].map(([channel, e]) => ({ channel, revenue: Number(e.revenue.toFixed(2)), quantity: e.quantity })).sort((a, b) => b.revenue - a.revenue)
      };
    };
    const current = summarize(year);
    const previous = summarize(year - 1);
    const monthly = rows.filter((r) => r.year === year).reduce((acc, r) => {
      acc[r.month] = (acc[r.month] ?? 0) + (Number(r.revenue) || 0);
      return acc;
    }, {});
    return jsonResult({
      current,
      previous,
      revenue_growth_pct: previous.revenue ? Number(((current.revenue - previous.revenue) / previous.revenue * 100).toFixed(2)) : null,
      monthly_revenue: Object.entries(monthly).map(([month, revenue]) => ({ month: Number(month), revenue: Number(revenue.toFixed(2)) })).sort((a, b) => a.month - b.month)
    });
  }
});

// src/lib/mcp/tools/park-events.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z7 } from "npm:zod@^3.25.76";
var park_events_default = defineTool7({
  name: "list_park_events",
  title: "Eventos do parque",
  description: "Lista os eventos do Hopi Hari (site oficial + cadastro manual) com datas, categoria, destaque e link, opcionalmente s\xF3 os ativos.",
  inputSchema: {
    only_active: z7.boolean().default(true).describe("Retornar apenas eventos ativos."),
    limit: z7.number().int().min(1).max(50).default(20).describe("Quantidade m\xE1xima de eventos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("park_events").select("slug,title,description,category,start_date,end_date,highlight,active,url,last_seen_at").order("start_date", { ascending: true, nullsFirst: false }).limit(limit ?? 20);
    if (only_active !== false) query = query.eq("active", true);
    const { data, error } = await query;
    if (error) return toolError(error.message);
    return jsonResult({ events: data ?? [], count: (data ?? []).length });
  }
});

// src/lib/mcp/index.ts
var projectRef = "ylduczowjvbtxixvakxx";
var mcp_default = defineMcp({
  name: "hopi-hari-insights",
  title: "Hopi Hari Insights",
  version: "0.1.0",
  instructions: "Ferramentas de leitura da plataforma Hopi Hari Insights: KPIs e melhores posts das redes sociais, crescimento de seguidores, reputa\xE7\xE3o (ReclameAqui/TripAdvisor), p\xFAblico e per capita do parque, vendas por canal e eventos. Todos os dados s\xE3o reais e ficam restritos ao usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    social_kpis_default,
    top_posts_default,
    follower_growth_default,
    reputation_default,
    park_performance_default,
    sales_overview_default,
    park_events_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
